[api]
port = "8000"
maxapikeys = 5
publicpath = "public/modpacks" 
manifest_name = manifest.json

[authentication]
secret = "thesecretkeyatpublicrepositoryuhauahaha"
aeskey = "abc&1*~#^2^#s0^=)^^7%b34"
expiration = 900