[api]
port = "8000"
apikey_header = "x-api-key"

[authentication]
secret = "secretket"
aeskey = "abc&1*~#^2^#s0^=)^^7%b34"
expiration = 900

[modpacks]
publicpath = "public/modpacks"
manifest_name = "manifest.json"

[user]
maxapikeys = 5