# //TODO: show the docker compose to Daniel.

version: '3.8'

services:
    # At this moment, we dont need a docker compose mapping the dockerfile. but we need a docker-compose to dev settings..
    #app:
        # container_name: api-modpack-boberto
        # build:
        #     context: .
        # ports:
        #     - 9000:80
        # environment:
        #     - PG_URI=postgres://root:test@postgree_hostname/test?sslmode=disable
        # volumes:
        #     - ./:/app/
        # restart: unless-stopped
        # tty: true
    postgres:
        image: postgres
        container_name: api-modpack-boberto-db
        hostname: postgree_hostname
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=test
            - POSTGRES_DB=test
        ports:
            - 5555:5432
        volumes:
            - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
        restart: unless-stopped
        healthcheck:
            test: [ "CMD", "pg_isready" ]
            interval: 10s
            timeout: 5s
            retries: 5

    ftpd_server:
        image: stilliard/pure-ftpd
        container_name: pure-ftpd
        ports:
        - "21:21"
        - "30000-30009:30000-30009"
        volumes:
        - "./test_shared/ftp:/home/username/"
        - "./test_shared/passwd:/etc/pure-ftpd/passwd"
        environment:
            PUBLICHOST: "localhost"
            FTP_USER_NAME: test
            FTP_USER_PASS: test
            FTP_USER_HOME: /home/username
        restart: always