# //TODO: show the docker compose to Daniel.

version: '3.8'

services:
    # At this moment, we dont need a docker compose mapping the dockerfile.
    # app:
    #     build: 
    #         context: .
    #     ports:
    #         - 9000:80
    #     environment:
    #         - PG_URI=postgres://root:test@postgree_hostname/test?sslmode=disable
    #     volumes:
    #         - ./:/app/
    #     restart: unless-stopped
    #     tty: true
    postgres:
        image: postgres
        hostname: postgree_hostname
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=test
            - POSTGRES_DB=test
        ports:
            - 5555:5432
        volumes:
            - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
        restart: unless-stopped
        healthcheck:
            test: [ "CMD", "pg_isready" ]
            interval: 10s
            timeout: 5s
            retries: 5
